## What are we going to cover

* TensorFlow basics & fundamentals

* Preprocessing data (getting it into tensors)

* Building and using pretrained deep learning models

* Fitting a model to the data (learning patterns)

* Making predictions with a model (using patterns)

* Evaluating model predictions

* Saving and loading models

* Using a trained model to make predictions on custom data

## Fundamentals concepts of Tensors with TensorFlow

What we're going to cover
TensorFlow is vast. But the main premise is simple: turn data into numbers (tensors) and build machine learning algorithms to find patterns in them.

In this notebook we cover some of the most fundamental TensorFlow operations, more specifically:

* Introduction to tensors (creating tensors)
* Getting information from tensors (tensor attributes)
* Manipulating tensors (tensor operations)
* Tensors and NumPy
* Using @tf.function (a way to speed up your regular Python functions)
* Using GPUs with TensorFlow
* Exercises to try

## Intoduction to Tensors 

In [1]:
# Import tensorFlow

import tensorflow as tf
tf.__version__

'2.8.0'

In [5]:
# Create tensors with tf.constant()

scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [6]:
# Check the number of dimension of a tensor (ndim stands for dimensions)

scalar.ndim

0

In [7]:
# Create a vector

vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [8]:
# check the dimension of vector
vector.ndim

1

In [9]:
# Create a matrix (more than 1 dimension)

matrix = tf.constant([[10, 7], 
                     [7, 10]])

matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [10]:
matrix.ndim

2

In [11]:

# Create another matrix and define the datatype
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [8., 9.]], dtype=tf.float16) # specify the datatype with 'dtype'
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [12]:
another_matrix.ndim


2

In [41]:
random_1 = tf.random.Generator.from_seed(42) # set the seed for reproducibility
random_1 = random_1.normal(shape=(3,3,3))
random_1

<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[-0.7565803 , -0.06854702,  0.07595026],
        [-1.2573844 , -0.23193763, -1.8107855 ],
        [ 0.09988727, -0.50998646, -0.7535805 ]],

       [[-0.57166284,  0.1480774 , -0.23362993],
        [-0.3522796 ,  0.40621263, -1.0523509 ],
        [ 1.2054597 ,  1.6874489 , -0.4462975 ]],

       [[-2.3410842 ,  0.99009085, -0.0876323 ],
        [-0.635568  , -0.6161736 , -1.9441465 ],
        [-0.48293006, -0.52447474, -1.0345329 ]]], dtype=float32)>

In [39]:
random_1.ndim

3